### ISSUE TITLE
Sample Rate Conversion

### ISSUE THREAD

**Issue by JuneToJuly** [Luc-Olsthoorn/TrueShot#1]
We need to convert the sample rate from a byte array to a double array.

We can use two different approaches:
1. Matlab calls from java. **NOPE**
2. Bit wise conversion

## UPDATE:
Ok, so when I was looking at reading data from the WAV file, we have the following to consider:

* Bits Per Sample 
* Buffer Size
* Bytes Per Frame

Bits per sample is just the number of bits that can be used to represent the sample. In our WAV case
we have a total of 16 bits per sample. This is a audio quality thing, don't need to know too many details.

Buffer Size can be anything. We are going to stick with the Matlab example for now, and say our Buffer Size is 5512 samples.

Bytes per frame was confusing at first, but it is just the number of samples per frame. In our case, we have 4 bytes per frame. So at 16 bits per sample(two bytes), we have two samples in each frame. Which makes sense because we are using WAV files, and they have stereo audio, left and right channel.

Sooo, now our sampling algorithm is: 

1. Read a total of 5512 * 2 bytes // We need double the size because we won't use half the bytes
2. Read each frame(4 bytes), grab only the first two bytes
3. Convert these two bytes to a double.

Converting the two bytes to a double is going to be a little weird. We may have to bit-wise build the double by going through the format
![Double](https://cdn.wccftech.com/wp-content/uploads/2015/02/Single-precision-and-double-precision-numbers-635x213.png)

Consider we read in the two bytes `0x47 0x1c` which are in little endian order.
Using a stadard Int_32 it would equal: 7239.
 The question we need to answer is how this translates to a double value.
 
[Link to hex converter which is useful](https://www.scadacore.com/tools/programming-calculators/online-hex-converter/)

# Update 2
The values are being stored like so:
> Sample Byte 1 | Sample Byte 2 | 0 | 0 | 0 | 0 | 0 | 0 |

The two bytes are shifted all the way to the exponent side, we need to ensure that we put them in the correct order (endianness).

[Link for checking what the double looks like in binary](http://www.binaryconvert.com/result_double.html?decimal=051046048053049055053055056049050053048048048048048101045048053)

**Comment by JuneToJuly** [comment]
Alrighty... so we can't use Matlab from java because it takes too long!

**Comment by UFWestlife** [comment]
I've got a discuss about our issue, https://stackoverflow.com/questions/15533854/converting-byte-array-to-double-array. Hope it will help.

**Comment by UFWestlife** [comment]
I'm still a little confused with the sample rate byte array. I remember it is a PCM_SIGNED, 5512*2 byte array but I can't get it when I debug my Matlab program. While I used a byte buffer to convert a byte array of a .wav file to a double array. It seems like the data format is what we want.
[https://www.dropbox.com/s/9rp2g45aaapakdo/Test.java?dl=0](url)
The input is like:
```
data len: 158760
First 100 line:
0.0
0.0
2.6463422257129E-310
-3.3045882513134177E275
3.2322213141984266E-148
6.840543304072628E294
-1.0901919192154263E228
.......
```
Wish it will help a little.

**Comment by JuneToJuly** [comment]
Thanks for the input Zun. I have discovered how to read our data the same way that Matlab is doing it by the following:
```java
byte[] sampledData = new byte[BUFFER_SIZE];
int bytesRead= 0;
while (bytesRead!= -1)
    {
    bytesRead = audioInputStream.read(sampledData, 0, sampledData.length);
    ByteBuffer byteBuffer = ByteBuffer.wrap(sampledData);
    double temp = 0;
    while(byteBuffer.remaining() >= 2)
    {
        // getting our sample
        temp = (double)((byteBuffer.get() & 0xff) | (byteBuffer.get() << 8)); 
        System.out.println("Count: " + count + "This is the value: " + temp);
        System.out.println("Count: " + count + "This is the value normalized: " 
                                                    + (temp / 32768.0));
        count++;
        byteBuffer.getShort(); // shuck the right channel
    }
```


So what we going on was we were loosing our sign value. 

Because bytes are signed, when we were converting to the double this property was being dropped. We mask them and it works. Now, to get values that match with the Matlab values, we have to normalize the sample data. Because our sample data is `16 bit`, `65536` total values to hold, ie `-32768 <-> 32768` if signed, we want a double such that `-1< Sample > 1`.
