### ISSUE TITLE
Elevation Gets Wrong Index

### ISSUE THREAD

**Issue by JuneToJuly** [Luc-Olsthoorn/TrueShot#7]
When creating your HRTF Session you specify the elevation. The calculation to find the closest elevation is wrong. For example, if you put -45, it should be index 0, but gives index 14, which is wrong.

**Comment by JuneToJuly** [comment]
Zun, thanks for finding the problem. Should I make the change? Or have you already done it?

**Comment by UFWestlife** [comment]
Haha you are welcome! Could you fix it on branch master ?
 I just changed it in my local codes but haven't push yet. And I'm not very sure that did I find all bugs and modified correctly.   
Thanks so much~!

**Comment by JuneToJuly** [comment]
Yes no problem!
